[package]
name = "mangalize-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "mangalize_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
mangalize-core = { path = "../crates/mangalize-core" }
mangalize-meta = { path = "../crates/mangalize-meta" }
mangalize-library = { path = "../crates/mangalize-library" }
mangalize-fetch = { path = "../crates/mangalize-fetch" }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde.workspace = true
serde_json.workspace = true
image.workspace = true
anyhow.workspace = true
tauri-plugin-updater = "2.11.0"
tauri-plugin-process = "2.3.1"
